#!/bin/sh
#
# Check if the program is running and produce expectable output.

if testcaldav  --stop > "$ADTTMP/run.log" 2>&1 ; then
    if grep -q scripts.tests.CalDAV.freebusy "$ADTTMP/run.log"; then
	echo "success: running testcaldav seem to work"
    else
	echo "error: output from testcaldav was not as expected"
    fi
else
    echo "error: unable to run testcaldav"
fi

cat "$ADTTMP/run.log"
