#!/bin/sh
#
# Check if the program is running and produce expected output.

set -e

retval=0

error() { retval=1; echo "error:" "$@"; }

./testcaldav.py  --stop > "$ADTTMP/run.log" 2>&1 || true

if grep -q scripts.tests.CalDAV "$ADTTMP/run.log"; then
    echo "success: running testcaldav seem to work"
else
    error "output from testcaldav was not as expected"
fi

cat "$ADTTMP/run.log"

exit $retval
