#!/bin/sh

set -e

CALDAVTESTDIR=/usr/share/caldavtester
export PYTHONPATH="$CALDAVTESTDIR"

# FIXME: needed for resource files
cd $CALDAVTESTDIR

$CALDAVTESTDIR/testcaldav.py      \
  -x $CALDAVTESTDIR/scripts/tests \
  "$@"

cd -
